CC = gcc
programa.o: main.o funcoes.o funcoesAux.o 
	$(CC) main.o funcoes.o funcoesAux.o -o programa.o
main.c: CCC.o funcoes.o funcoesAux.o
	$(CC) main.o funcoes.o funcoesAux.o -o programa.o
	 
funcoes.o :

	
	